### ISSUE TITLE
重学mdn-CSS篇

### ISSUE THREAD

**Issue by xiangyuisabatman** [xiangyuisabatman/xiangyuisabatman#2]
- CSS究竟是怎么工作的

> 		1. 浏览器载入HTML文件
> 		2. 将HTML文件转化为一个DOM，DOM是文件在计算机内存中的表现形式。
> 		3. 浏览器会拉取该HTML相关的大部分资源，比如嵌入到页面的图片、视频、CSS样式。JavaScript会稍后进行处理。
> 		4. 浏览器拉取到CSS之后会进行解析，根据选择器的不同类型把他们分到不同的“桶”中。浏览器基于它找到的不同的选择器，将不同的规则应用在对应的DOM节点中，并添加节点依赖的样式（这个中间步骤称为渲染树）。
> 		5. 上述的规则应用于渲染树之后，渲染树会依照应该出现的结构进行布局。

---

- em和rem

> - em作用在font-size上时，相对于父元素的字体大小，再其他属性上使用是相对于自身的字体大小。
> - rem是相对于根元素的字体大小。

---

- 清除浮动

```css
/**
	1. 
	*/
.wrapper::after {
  content: "";
  clear: both;
  display: block;
}
/**
	2. 
	*/
.wrapper {
  background-color: rgb(79, 185, 227);
  padding: 10px;
  color: #fff;
  overflow: auto; // clearfix
}
/**
	3. 较现代的方案 flow-root
	*/
.wrapper {
  background-color: rgb(79, 185, 227);
  padding: 10px;
  color: #fff;
  display: flow-root; // clearfix
}
```
