### ISSUE TITLE
使用github actions 管理代码并上传到服务器docker中运行

### ISSUE THREAD

**Issue by xiangyuisabatman** [xiangyuisabatman/xiangyuisabatman#5]
## 流程

1. 将本地代码上传到github仓库
2. 利用github actions执行代码操作
   1. 打包项目
   2. 将项目包上传到服务器
   3. 刷新服务器容器，生成新的镜像
3. 访问服务器地址成功

---

### 密钥生成

在服务器控制台生成ssh-keygen

```sh
1. 生成ssh-keygen
[root@host ~]$ ssh-keygen
2. 服务器上添加公钥
[root@host ~]$ cd .ssh
[root@host .ssh]$ cat id_rsa.pub >> authorized_keys
3. 修改权限
[root@host .ssh]$ chmod 600 authorized_keys
[root@host .ssh]$ chmod 700 ~/.ssh
4. 设置 SSH，打开密钥登录功能
RSAAuthentication yes
PubkeyAuthentication yes
PermitRootLogin yes
5. 重启ssh
[root@host .ssh]$ service sshd restart
6. 将私钥转换成pem格式(打开id_rsa，看看开头是不是-----BEGIN RSA PRIVATE KEY-----)
[root@host .ssh]$ ssh-keygen -p -f ~/.ssh/id_rsa -m pem
```

### github添加私钥

复制服务器上的id_rsa文件内容，打开`github repositories` => `github actions` => `settings` => `secrets and variables` => `actions` => `new repository secret`

设置Name=`SSH_PRIVATE_KEY`，把id_rsa的内容复制的下面

### 编写workflows

```yaml
name: Build And Deploy foodmap-node

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js 20.10.0
        uses: actions/setup-node@master
        with:
          node-version: 20.10.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.11.0

      - name: Compress Dist Folder
        run: zip -r dist.zip . -x 'node_modules/*' -x 'logs/*'

      # 部署到服务器
      - name: deploy
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 本地.ssh文件下的私钥id_rsa，存在secrets的PRIVATE_KEY中
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          SOURCE: './dist.zip'
          # 服务器域名/IP
          REMOTE_HOST: ${{ secrets.ALI_HOST }}
          # 服务器默认用户名为root
          REMOTE_USER: 'root'
          # 目标目录
          TARGET: '/usr/local/src/node'
          # 排除目录
          EXCLUDE: '/node_modules/'

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ALI_HOST }}
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
          	# 解压缩包到服务器目录下
            unzip -o /usr/local/src/node/dist.zip -d /usr/local/src/node/
            # 删除压缩包
            rm /usr/local/src/node/dist.zip
            cd /usr/local/src/node/
            # 生成镜像包
            docker build -t node-image .
            # 每次启动前删除之前创造的镜像
            docker stop node-image
            docker remove node-image
            # 启动服务
            docker run --name node-container -d -p 7001:7001 node-image
            docker ps -a

```

### 客户端请求云服务器上docker中的node服务

1. 设置云服务器上nginx配置

```js
location /api {
    proxy_pass docker容器的ip:端口号;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;
}

// 获取容器的ip
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container_name_or_id>
```

2. 设置云服务器安全组保证端口号允许访问
